products/urls.py
from django.urls import path, include

from products.views import products

app_name = 'products'

urlpatterns = [
    path('', products, name='index')
]

store/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

from products.views import index

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', index, name='index'),               # добавляем путь к файлу чтобы он мог отображаться в проекте
    path('products/', include('products.urls', namespace='products')),               # добавляем путь к файлу чтобы он мог отображаться в проекте
    path('users/', include('users.urls', namespace='users')),
]

if settings.DEBUG:
    urlpatterns == static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import path, include

from users.views import login, registration, profile, logout

app_name = 'users'

urlpatterns = [
    path('login/', login, name='login'),      # .../users/login/
    path('registration/', registration, name='registration'),
    path('profile/', profile, name='profile'),
    path('logout/', logout, name='logout'),
]

products/models.py
from django.db import models


# для того чтобы указать что эти классы будут затем использоваться для создание таблиц БД
# с параметрах указывается models.Model
class ProductCategory(models.Model):
    # так как мы используем эти поля для создания БД(а в них требуется указывать тип данных)
    # мы через класс models указываем тип данных и его параметры
    name = models.CharField(max_length=128, unique=True)
    description = models.TextField(null=True, blank=True)

    def __str__(self):
        return self.name


class Product(models.Model):
    name = models.CharField(max_length=256)
    description = models.TextField()
    price = models.DecimalField(max_digits=6, decimal_places=2)
    quantity = models.PositiveIntegerField(default=0)
    image = models.ImageField(upload_to='products_images')
    category = models.ForeignKey(to=ProductCategory, on_delete=models.CASCADE)

    # прописываем для изменения отображения в админке
    def __str__(self):
        return f'Продукт: {self.name} | Категория: {self.category.name}'

users/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser


class User(AbstractUser):
    image = models.ImageField(upload_to='users_images', null=True, blank=True)

users/forms.py
from django import forms
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm, UserChangeForm

from users.models import User


class UserLoginForm(AuthenticationForm):
    username = forms.CharField(widget=forms.TextInput(attrs={
        'class': 'form-control py-4',
        'placeholder': 'Введите имя пользователя'}))
    password = forms.CharField(widget=forms.PasswordInput(attrs={
        'class': 'form-control py-4',
        'placeholder': 'Введите пароль'}))

    class Meta:
        model = User
        fields = ('username', 'password')


class UserRegistrationForm(UserCreationForm):
    first_name = forms.CharField(widget=forms.TextInput(attrs={
        'class': 'form-control py-4',
        'placeholder': 'Введите имя'}))
    last_name = forms.CharField(widget=forms.TextInput(attrs={
        'class': 'form-control py-4',
        'placeholder': 'Введите фамилию'}))
    username = forms.CharField(widget=forms.TextInput(attrs={
        'class': 'form-control py-4',
        'placeholder': 'Введите имя пользователя'}))
    email = forms.CharField(widget=forms.EmailInput(attrs={
        'class': 'form-control py-4',
        'placeholder': 'Введите адрес эл. почты'}))
    password1 = forms.CharField(widget=forms.PasswordInput(attrs={
        'class': 'form-control py-4',
        'placeholder': 'Введите пароль'}))
    password2 = forms.CharField(widget=forms.PasswordInput(attrs={
        'class': 'form-control py-4',
        'placeholder': 'Подтвердите пароль'}))

    class Meta:
        model = User
        fields = ('first_name', 'last_name', 'username', 'email', 'password1', 'password2')


class UserProfileForm(UserChangeForm):
    first_name = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control py-4'}))
    last_name = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control py-4'}))
    image = forms.ImageField(widget=forms.FileInput(attrs={'class': 'custom-file-input'}), required=False)
    username = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control py-4', 'readonly': True}))
    email = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control py-4', 'readonly': True}))

    class Meta:
        model = User
        fields = ('first_name', 'last_name', 'image', 'username', 'email')

products/views.py
from django.shortcuts import render

from products.models import ProductCategory, Product


def index(request):
    context = {'title': 'Store'}
    return render(request, 'products/index.html', context)


def products(request):
    context = {
        'title': 'Store - Каталог',
        'products': Product.objects.all(),
        'categories': ProductCategory.objects.all(),
    }
    return render(request, 'products/products.html', context)

users/views.py
from django.shortcuts import render, HttpResponseRedirect
from django.contrib import auth, messages
from django.urls import reverse

from users.forms import UserLoginForm, UserRegistrationForm, UserProfileForm


def login(request):
    if request.method == 'POST':
        form = UserLoginForm(data=request.POST)
        if form.is_valid():                             # ввод введеных данных пользователем
            username = request.POST['username']
            password = request.POST['password']
            user = auth.authenticate(username=username, password=password)
            if user:                                    # проверка на наличие пользователя в базе
                auth.login(request, user)
                return HttpResponseRedirect(reverse('index'))
    else:
        form = UserLoginForm()
    context = {'form': form}
    return render(request, 'users/login.html', context)


def registration(request):
    if request.method == 'POST':
        form = UserRegistrationForm(data=request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, 'Поздравляем! Вы зарегались')
            return HttpResponseRedirect(reverse('users:login'))
    else:
        form = UserRegistrationForm()
    context = {'form': form}
    return render(request, 'users/registration.html', context)


def profile(request):
    if request.method == 'POST':
        form = UserProfileForm(instance=request.user, data=request.POST, files=request.FILES)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('users:profile'))
        else:
            print(form.errors)
    else:
        form = UserProfileForm(instance=request.user)
    context = {'title': 'Store - Профиль', 'form': form}
    return render(request, 'users/profile.html', context)


def logout(request):
    auth.logout(request)
    return HttpResponseRedirect(reverse('index'))

products/templates/products/base.html
{% load static %}


<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>{{ title }}</title>

    <!-- Bootstrap core CSS -->
    <link href="{% static 'vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">

    <!-- Custom styles for this template -->
    {% block css %}  {% endblock %}

</head>

<body>

<!-- Navigation -->
<nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top">
    <div class="container">
        <a class="navbar-brand" href="{% url 'index' %}">Store</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive"
                aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarResponsive">
            <ul class="navbar-nav ml-auto">
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'products:index' %}">Каталог <i class="fas fa-shopping-bag"></i> </a>
                </li>
                {% if user.is_authenticated %}
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button"
                           data-bs-toggle="dropdown" aria-expanded="false">
                            <i class="fas fa-user-circle"></i>
                        </a>
                        <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                            <li>
                                <a class="dropdown-item" href="{% url 'users:profile' %}">Профиль</a>
                            </li>
                            <li><a class="dropdown-item" href="orders/orders.html">Заказы</a></li>
                            {% if user.is_superuser or user.is_staff %}
                                <li><a class="dropdown-item" href="{% url 'admin:index' %}">
                                    Админ-панель
                                </a></li>
                            {% endif %}
                            <li>
                                <hr class="dropdown-divider">
                            </li>
                            <li>
                                <a class="dropdown-item" href="{% url 'users:logout' %}">
                                    Выйти
                                </a>
                            </li>
                        </ul>
                    </li>
                {% else %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'users:login' %}">Войти <i class="fas fa-sign-in-alt"></i></a>
                    </li>
                {% endif %}
            </ul>
        </div>
    </div>
</nav>

{% block content %}  {% endblock %}

{% block footer %}  {% endblock %}

<!-- Bootstrap core JavaScript -->
<script src="{% static 'vendor/jquery/jquery.min.js' %}"></script>
<script src="{% static 'vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p"
        crossorigin="anonymous"></script>

<!-- FontAwesome script -->
<script src="{% static 'vendor/fontawesome/fontawesome-icons.js' %}" crossorigin="anonymous"></script>

</body>

</html>

products/templates/products/index.html
{#тег для наследования от родительского шаблона#}
{% extends 'products/base.html' %}
{#его прописываем отельно так как он не наследуется#}
{% load static %}

{% block css %}
    <link href="{% static 'vendor/css/index.css' %}" rel="stylesheet">
{% endblock %}

{% block content %}
    <section>
    <!--    <div class="alert alert-light text-center" role="alert">-->
    <!--        Информационное сообщение-->
    <!--    </div>-->
    <div class="container">
        <div class="row">
            <div class="col-lg-6">
                <h1 class="mt-5">Store</h1>
                <p>
                    Новые образы и лучшие бренды на Store.
                    Бесплатная доставка по всему миру! Аутлет: до -70% Собственный бренд. -20% новым покупателям.
                </p>
                <button id="start-purchase-btn" type="button" class="btn btn-lg">
                    <a id="start-purchase-link" href="{% url 'products:index' %}">
                        Начать покупки
                    </a>
                </button>
            </div>
        </div>
    </div>
</section>
{% endblock %}

products/templates/products/products.html
{% extends 'products/base.html' %}
{% load static %}

{% block css %}
    <link href="{% static 'vendor/css/products.css' %}" rel="stylesheet">
{% endblock %}

{% block content %}
    <div class="container">

    <div class="row">

        <div class="col-lg-3">

            <h1 class="my-4">Store</h1>
            <div class="list-group">
                {% for category in categories %}
                    <a href="#" class="list-group-item">{{ category.name }}</a>
                {% endfor %}
            </div>

        </div>
        <!-- /.col-lg-3 -->

        <div class="col-lg-9">

            <div id="carouselExampleIndicators" class="carousel slide my-4" data-ride="carousel">
                <ol class="carousel-indicators">
                    <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
                    <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
                    <li data-target="#carouselExampleIndicators" data-slide-to="2"></li>
                </ol>
                <div class="carousel-inner" role="listbox">
                    <div class="carousel-item active">
                        <img class="d-block img-fluid" src="{% static 'vendor/img/slides/slide-1.jpg' %}" alt="First slide">
                    </div>
                    <div class="carousel-item">
                        <img class="d-block img-fluid" src="{% static 'vendor/img/slides/slide-2.jpg' %}" alt="Second slide">
                    </div>
                    <div class="carousel-item">
                        <img class="d-block img-fluid" src="{% static 'vendor/img/slides/slide-3.jpg' %}" alt="Third slide">
                    </div>
                </div>
                <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
                    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                    <span class="sr-only">Previous</span>
                </a>
                <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
                    <span class="carousel-control-next-icon" aria-hidden="true"></span>
                    <span class="sr-only">Next</span>
                </a>
            </div>

            <div class="row">

                {% for product in products %}
                    <div class="col-lg-4 col-md-6 mb-4">
                    <div class="card h-100">
                        <a href="#">
                            <img class="card-img-top"
                                 src="{{ product.image.url }}"
                                 alt="">
                        </a>
                        <div class="card-body">
                            <h4 class="card-title">
                                <a href="#">{{ product.name }}</a>
                            </h4>
                            <h5>{{ product.price }} руб.</h5>
                            <p class="card-text">{{ product.description }}</p>
                        </div>
                        <div class="card-footer text-center">
                            <button type="button" class="btn btn-outline-success">Отправить в корзину</button>
                        </div>
                    </div>
                </div>
                {% endfor %}

            </div>

            <nav aria-label="Page navigation example">
                <ul class="pagination justify-content-center">
                    <li class="page-item disabled">
                        <a class="page-link" href="#" tabindex="-1" aria-disabled="true">Previous</a>
                    </li>
                    <li class="page-item"><a class="page-link" href="#">1</a></li>
                    <li class="page-item"><a class="page-link" href="#">2</a></li>
                    <li class="page-item"><a class="page-link" href="#">3</a></li>
                    <li class="page-item">
                        <a class="page-link" href="#">Next</a>
                    </li>
                </ul>
            </nav>

        </div>

    </div>

</div>
{% endblock %}

{% block footer %}
    <footer class="py-5 bg-dark">
        <div class="container">
            <p class="m-0 text-center text-white">Copyright &copy; Store 2022</p>
        </div>
</footer>
{% endblock %}

users/templates/users/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8"/>
    <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no"/>
    <meta name="description" content=""/>
    <meta name="author" content=""/>
    <title>Store - Авторизация</title>
    <link href="{% static 'vendor/css/auth.css' %}" rel="stylesheet"/>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.1/js/all.min.js"
            crossorigin="anonymous"></script>
</head>
<body class="bg-primary">
<div id="layoutAuthentication">
    <div id="layoutAuthentication_content">
        {%  block content %} {% endblock %}
    </div>
</div>
<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js"
        crossorigin="anonymous"></script>
<script src="{% static 'vendor/js/auth-admin.js' %}"></script>
</body>
</html>

users/templates/users/login.html
{% extends 'users/base.html' %}

{% block content %}
    <main>
        <div class="container">
            <div class="row justify-content-center">
                <div class="col-lg-5">
                    {% if messages or form.non_field_errors %}
                        <div class="alert {% if messages %} alert-success {% else %} alert-warning {% endif %} alert-dismissible fade show" role="alert"
                             style="margin-top: 50px;">
                            {% if messages %}
                                {% for message in messages %}
                                    {{ message }}
                                {% endfor %}
                            {% else %}
                                {{ form.non_field_errors }}
                            {% endif %}
                            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                <span aria-hidden="true">&times;</span>
                            </button>
                        </div>
                    {% endif %}
                    <div class="card shadow-lg border-0 rounded-lg mt-5">
                        <div class="card-header"><h3 class="text-center font-weight-light my-4">Авторизация</h3>
                        </div>
                        <div class="card-body">
                            <form action="{% url 'users:login' %}" method="post">
                                {% csrf_token %}
                                <div class="form-group">
                                    <label class="small mb-1" for="{{ form.username.id_for_label }}">
                                        Имя пользователя
                                    </label>
                                    {{ form.username }}
                                </div>
                                <div class="form-group">
                                    <label class="small mb-1" for="{{ form.password.id_for_label }}">
                                        Пароль
                                    </label>
                                    {{ form.password }}
                                </div>
                                <div class="form-group d-flex align-items-center justify-content-between mt-4 mb-0">
                                    <a class="small" href="#">Забыли пароль?</a>
                                    <input class="btn btn-primary" type="submit" value="Авторизоваться">
                                </div>
                                <div class="form-group d-flex align-items-center justify-content-between mt-4 mb-0">
                                    <a href="#">
                                        <i class="fab fa-google fa-2x" style="color: #d9503e;"></i>
                                    </a>
                                    <a href="#">
                                        <i class="fab fa-vk fa-2x" style="color: #4a658b;"></i>
                                    </a>
                                    <a href="#">
                                        <i class="fab fa-github fa-2x" style="color: #303030;"></i>
                                    </a>
                                    <a href="#">
                                        <i class="fab fa-facebook fa-2x" style="color: #405794;"></i>
                                    </a>
                                </div>
                            </form>
                        </div>
                        <div class="card-footer text-center">
                            <div class="small"><a href="{% url 'users:registration' %}">Нужен аккаунт? Зарегистрируйся!</a></div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </main>
{% endblock %}

users/templates/users/profile.html
{% extends 'products/base.html' %}
{% load static %}

{% block css %}
    <link href="{% static 'vendor/css/profile.css' %}" rel="stylesheet">
{% endblock %}

{% block content %}
    <div class="container">
    <div class="row">
        <div class="col-lg-7">
            <h4 class="mt-3 mb-3">Профиль</h4>
            <div class="col-lg-12 text-center">
                <img width="100" height="100"
                     src="{% if user.image %} {{ user.image.url }} {% else %} {% static 'vendor\img\users\default_avatar.jpg' %} {% endif %}"
                     class="img-thumbnail">
            </div>
            <form action="{% url 'users:profile' %}" method="post" enctype="multipart/form-data">
                {% csrf_token %}
                <div class="form-row">
                    <div class="col-lg-6">
                        <div class="form-group">
                            <label class="small mb-1" for="{{ form.first_name.id_for_label }}">Имя</label>
                            {{ form.first_name }}
                        </div>
                    </div>
                    <div class="col-lg-6">
                        <div class="form-group">
                            <label class="small mb-1" for="{{ form.last_name.id_for_label }}">Фамилия</label>
                            {{ form.last_name }}
                        </div>
                    </div>
                </div>
                <div class="form-row mb-2">
                    <div class="col-lg-12">
                        <div class="custom-file">
                            {{ form.image }}
                            <label class="custom-file-label" for="{{ form.image.id_for_label }}">
                                Выберите изображение
                            </label>
                        </div>
                    </div>
                </div>
                <div class="form-row">
                    <div class="col-lg-6">
                        <label class="small mb-1" for="{{ form.username.id_for_label }}">Имя пользователя</label>
                        {{ form.username }}
                    </div>
                    <div class="col-lg-6">
                        <label class="small mb-1" for="{{ form.email.id_for_label }}">
                            Адрес электронной почты
                        </label>
                        {{ form.email }}
                    </div>
                </div>
                <div class="form-row">
                    <div class="col-lg-12" style="margin-top: 33px;">
                        <input class="btn btn-info btn-block" type="submit" value="Сохранить">
                    </div>
                </div>
            </form>
        </div>
        <div class="col-lg-5">
            <h4 class="mt-3 mb-3 d-flex justify-content-between align-items-center mb-3">
                Корзина <span class="badge badge-secondary badge-pill">3</span>
            </h4>
            <div class="card mb-3">
                <div class="card-body">
                    <h5 class="card-title">Product name</h5>
                    <p class="card-text">Product description</p>
                </div>
                <ul class="list-group list-group-flush">
                    <li class="list-group-item bg-light">
                        <div class="row text-center">
                            <div class="col-lg-4">
                                <input name="basketID" type="number" class="form-control"
                                       value="1" min="0">
                            </div>
                            <div class="col-lg-4">2 390 руб.</div>
                            <div class="col-lg-4">
                                <a href="#">
                                    <i class="fas fa-trash"></i>
                                </a>
                            </div>
                        </div>
                    </li>
                </ul>
            </div>
            <div class="card mb-3">
                <div class="card-footer">
                    <p class="float-left">Итого</p>
                    <h4 class="float-right">2 390 руб.</h4>
                </div>
            </div>
            <a class="btn btn-success btn-lg float-right" href="../orders/order-create.html">
                Оформить заказ
            </a>
        </div>
    </div>
</div>
{% endblock %}

users/templates/users/registration.html
{% extends 'users/base.html' %}

{% block content %}
    <main>
        <div class="container">
            <div class="row justify-content-center">
                <div class="col-lg-7">
                    {% if form.errors %}
                        <div class="alert alert-warning alert-dismissible fade show" role="alert"
                             style="margin-top: 50px;">
                            {{ form.errors }}
                            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                <span aria-hidden="true">&times;</span>
                            </button>
                        </div>
                    {% endif %}
                    <div class="card shadow-lg border-0 rounded-lg mt-5">
                        <div class="card-header"><h3 class="text-center font-weight-light my-4">Создать аккаунт</h3>
                        </div>
                        <div class="card-body">
                            <form action="{% url 'users:registration' %}" method="post">
                                {% csrf_token %}
                                <div class="form-row">
                                    <div class="col-md-6">
                                        <div class="form-group">
                                            <label class="small mb-1" for="{{ form.first_name.id_for_label }}">
                                                Имя
                                            </label>
                                            {{ form.first_name }}
                                        </div>
                                    </div>
                                    <div class="col-md-6">
                                        <div class="form-group">
                                            <label class="small mb-1" for="{{ form.last_name.id_for_label }}">
                                                Фамилия
                                            </label>
                                            {{ form.last_name }}
                                        </div>
                                    </div>
                                </div>
                                <div class="form-row">
                                    <div class="col-md-6">
                                        <label class="small mb-1" for="{{ form.username.id_for_label }}">
                                            Имя пользователя
                                        </label>
                                        {{ form.username }}
                                    </div>
                                    <div class="col-md-6">
                                        <label class="small mb-1" for="{{ form.email.id_for_label }}">
                                            Адрес электронной почты
                                        </label>
                                        {{ form.email }}
                                    </div>
                                </div>
                                <div class="form-row">
                                    <div class="col-md-6">
                                        <div class="form-group">
                                            <label class="small mb-1" for="{{ form.password1.id_for_label }}">
                                                Пароль
                                            </label>
                                            {{ form.password1 }}
                                        </div>
                                    </div>
                                    <div class="col-md-6">
                                        <div class="form-group">
                                            <label class="small mb-1" for="{{ form.password2.id_for_label }}">
                                                Подтверждение пароля
                                            </label>
                                            {{ form.password2 }}
                                        </div>
                                    </div>
                                </div>
                                <div class="form-group mt-4 mb-0">
                                    <input class="btn btn-primary btn-block" type="submit" value="Создать аккаунт">
                                </div>
                            </form>
                        </div>
                        <div class="card-footer text-center">
                            <div class="small"><a href="{% url 'users:login' %}">
                                Уже есть аккаунт? Авторизоваться
                            </a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </main>
{% endblock %}